# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 47bac445313f2af85450e95a995f2f4edb20f2370fca15f01a6880c8d5318148592787ac3654f70e0005afac29685cce5985c975fcad04053a766ac07ee5c6a8

test:
  secret_key_base: 3605b5b313f4bd21896a40fa2fb338742ffb2984c70987b314dc2d6e975c6e350abe209a3b01c868d6f864d45f3210d1735cdde59f31bd552ff8ba03cd077d3e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
